name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Verificar estrutura
        run: |
          test -f index.html
          test -d src/js
          test -d src/css
          test -d src/img

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Validar Sintaxe JavaScript
        run: |
          for file in $(find src/js -name "*.js"); do
            echo "Validando arquivo $file"
            node --check "$file" || exit 1
          done

      - name: Validar HTML com htmlhint
        run: |
          npm install -g html-validate
          html-validate index.html