name: Pipeline Integração e Entrega Contínua (CI/CD)

# Pipeline executa a cada push na branch main
on:
  push:
    branches:
      - main

jobs:
  # Build inicial do projeto
  build:
    runs-on: ubuntu-latest # Utiliza ubuntu para rodar pipeline

    steps:
      # Faz checkout no codigo do projeto
      - name: Checkout do código
        uses: actions/checkout@v6

      # Como o projeto é simples e não possui dependências, apenas verifica estrutura
      - name: Verificar estrutura
        run: |
          test -f index.html
          test -d src/js
          test -d src/css
          test -d src/img

  # Testes ao buildar projeto
  test:
    runs-on: ubuntu-latest # Utiliza ubuntu para rodar pipeline
    needs: build

    steps:
      # Faz checkout no codigo do projeto
      - name: Checkout do código
        uses: actions/checkout@v6

      # Instala o node js
      - name: Instalar Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
      
      # Instala o html-validate
      - name: Instalar html-validate
        run: npm install -g html-validate
      
      # Instalar Terraform
      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v4

      # Utiiliza o node para validar arquivos javascript
      - name: Validar Sintaxe JavaScript
        run: |
          for file in $(find src/js -name "*.js"); do
            echo "Validando arquivo $file"
            node --check "$file" || exit 1
          done

      # Utiliza html-validate para validar arquivo index.html
      - name: Validar HTML com htmlhint
        run: html-validate index.html

      # Inicializar Terraform
      - name: Terraform Init
        run: terraform -chdir=infra init

      # Validar arquivos Terraform (.tf)
      - name: Terraform Validate
        run: terraform -chdir=infra validate
  
  # Deploy do projeto
  deploy:
    runs-on: ubuntu-latest # Utiliza ubuntu para rodar pipeline
    needs: test

    steps:
      # Faz checkout no codigo do projeto
      - name: Checkout do código
        uses: actions/checkout@v6

      # Configura as credenciais de acesso ao bucket na AWS
      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Faz o deploy dos arquivos sincronizados para S3
      - name: Deploy para S3
        run: |
          aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }} \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "infra/*" \
            --exclude "*.md"